refactor: set the "deepin_anything_server" user to system user
Change-Id: I7f4662ba78d65755fed00ff8617bb2b8c159313a

diff --git a/debian/deepin-anything-server.postinst b/debian/deepin-anything-server.postinst
--- a/debian/deepin-anything-server.postinst
+++ b/debian/deepin-anything-server.postinst
@@ -10,12 +10,11 @@ if [ "$action" = configure ]; then
     if [ $? = 0 ]
     then
         set -e
-        usermod -s /usr/sbin/nologin $user
-        exit 0
+        userdel $user
     fi
 
     set -e
-    useradd -M -s /usr/sbin/nologin $user || (echo "Failed on add user deepin_anything_server" && false)
+    useradd -M -r -s /sbin/nologin $user || (echo "Failed on add user deepin_anything_server" && false)
 fi
 
 #DEBHELPER#
