refactor: use systemd.sysusers.d to manager "deepin-anything-server" user
Change-Id: I19917f3b330ecbbdab2031e31044f6b8faad4fc5

diff --git a/debian/deepin-anything-server.postinst b/debian/deepin-anything-server.postinst
--- a/debian/deepin-anything-server.postinst
+++ b/debian/deepin-anything-server.postinst
@@ -3,9 +3,9 @@
 action="$1"
 
 if [ "$action" = configure ]; then
-    # add user "deepin_anything_server"
+    # add user "deepin-anything-server"
     #create user if not exists
-    user=deepin_anything_server
+    user=deepin-anything-server
     id $user >& /dev/null
     if [ $? = 0 ]
     then
@@ -13,7 +13,7 @@ if [ "$action" = configure ]; then
     fi
 
     set -e
-    useradd -M -r -s /sbin/nologin $user || (echo "Failed on add user deepin_anything_server" && false)
+    useradd -M -r -s /sbin/nologin $user || (echo "Failed on add user deepin-anything-server" && false)
 fi
 
 #DEBHELPER#
diff --git a/debian/deepin-anything-server.postrm b/debian/deepin-anything-server.postrm
--- a/debian/deepin-anything-server.postrm
+++ b/debian/deepin-anything-server.postrm
@@ -5,8 +5,8 @@ set -e
 action="$1"
 
 if [ "$action" = remove ]; then
-	# del user "deepin_anything_server"
-	userdel deepin_anything_server || (echo "Failed on delete user deepin_anything_server" && false)
+	# del user "deepin-anything-server"
+	userdel deepin-anything-server || (echo "Failed on delete user deepin-anything-server" && false)
 fi
 
 #DEBHELPER#
