feat: deepin-anything-tool use system bus
deepin-anything-tool:
 * change cache path to /var/cache/deepin/deepin-anything
 * exec in "deepin-anything-server" user

Change-Id: I545d8d95fc6603c7d08979a09ff5f02c20f2a6e8

diff --git a/debian/deepin-anything-server.postinst b/debian/deepin-anything-server.postinst
--- a/debian/deepin-anything-server.postinst
+++ b/debian/deepin-anything-server.postinst
@@ -7,13 +7,16 @@ if [ "$action" = configure ]; then
     #create user if not exists
     user=deepin-anything-server
     id $user >& /dev/null
-    if [ $? = 0 ]
+    if [ $? -ne 0 ]
     then
-        exit 0
+        set -e
+        useradd -M -r -s /sbin/nologin $user || (echo "Failed on add user deepin-anything-server" && false)
     fi
 
-    set -e
-    useradd -M -r -s /sbin/nologin $user || (echo "Failed on add user deepin-anything-server" && false)
+    if [ ! -d "/var/cache/deepin/deepin-anything" ]; then
+        mkdir /var/cache/deepin/deepin-anything
+        chown deepin-anything-server:deepin-anything-server /var/cache/deepin/deepin-anything
+    fi
 fi
 
 #DEBHELPER#
